### ISSUE TITLE
Default Download/Upload Units

### ISSUE THREAD

**Issue by ksnell88** [barrycarey/Speedmon#10]
I have been using Speedtest/InfluxDB1 for a while and recently migrated to Speedmon/InfluxDB2. What are the default upload/download units used for Speedmon? I can't seem to figure out how to covert it to Mbps for Grafana.

I'm getting `_value`s returned around 25,137,682 when my connection speed is 200Mbps so it doesn't seem like the units are bits.

**Comment by tempomode** [comment]
It's in bytes - 25137682 bytes is ~201.1Mbps

**Comment by ksnell88** [comment]
Thank you!
